# Generated by Django 3.0.8 on 2020-07-02 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, null=True)),
                ('priority', models.IntegerField(default='3')),
                ('due_date', models.DateTimeField(null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todoapp.Registration')),
            ],
        ),
    ]
