# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todolist_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
    ]
