# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_todolist_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='priority',
            field=models.IntegerField(default='3'),
        ),
    ]
