# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todolist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
