# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
