# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_auto_20170428_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
