# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20170428_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='user_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
