# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_auto_20170428_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='todoapp.Registration'),
            preserve_default=False,
        ),
    ]
