# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0011_registration_confirm_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='confirm_signup',
            new_name='email_verified',
        ),
    ]
