# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0012_auto_20170512_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email_active',
            field=models.BooleanField(default=True),
        ),
    ]
